name: CI Pipeline  

on:  
  push: 
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4
      - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: yassw
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Backend
      run: docker build -t spring-app:latest ./springboot
      - name: Build Frontend
      run: docker build -t angular-app:latest ./angular-app
      - name: Tag Backend
      run: docker tag spring-app:latest yassw/spring-app:latest
      - name: Tag Frontend
      run: docker tag angular-app:latest yassw/angular-app:latest
      - name: Push Backend
      run: docker push yassw/spring-app:latest

      - name: Push Frontend
      run: docker push yassw/angular-app:latest
      - name: Run Docker Compose
      run: |
        docker-compose up -d
        sleep 20
        docker ps
