name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Spring Boot with Maven
        run: |
          cd springboot/app
          mvn clean package -DskipTests

      - name: Build Backend
        run: docker build -t spring-app:latest ./springboot/app

      - name: Build Frontend
        run: docker build -t angular-app:latest ./angular-app

      - name: Tag Backend
        run: docker tag spring-app:latest yassw/spring-app:latest

      - name: Tag Frontend
        run: docker tag angular-app:latest yassw/angular-app:latest

      - name: Push Backend
        run: docker push yassw/spring-app:latest

      - name: Push Frontend
        run: docker push yassw/angular-app:latest

      - name: Run Docker Compose
        run: |
          docker compose up -d
          docker ps

      - name: Vérifier les conteneurs
        run: |
          docker ps
          docker-compose ps

